@startuml
    top to bottom direction

    skinparam class {
        BackgroundColor White
        BorderColor #fd891c
        ArrowColor #808285
    }
    skinparam note {
        BackgroundColor #ffcc00
        BorderColor #ff6665
    }
    skinparam stereotypeCBackgroundColor #9d65a9
    skinparam shadowing false

    note "Maps URL to App state" as RouterNote
    note "Contains App state\nand user data" as AppStateModelNote
    note "Choose current representation\ndependin on the state,\nsetup and interacting with DOM" as ViewNote

    class Router
    Router : -routes
    Router : -gotoStart()
    Router : -gotoSuccess()
    Router : -gotoError()

    class AppStateModel
    AppStateModel : -state
    AppStateModel : -userName
    AppStateModel : -correctNamesList
    AppStateModel : +set(fields)
    AppStateModel : +get(field)
    AppStateModel : +isNameValid(userName)

    class View
    View : -templates
    View : +render()
    View : -checkName()

    Router .. RouterNote
    AppStateModel .. AppStateModelNote
    View .. ViewNote

    Router --> "set state" AppStateModel

    AppStateModel <--> "get/set username, state" View
    AppStateModel ..> "listen to state change" View
@enduml
